name: Deploy Lambda Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t lambda-docker-deploy .
          docker tag lambda-docker-deploy:latest <account-id>.dkr.ecr.<region>.amazonaws.com/lambda-docker-repo:latest
          docker push <account-id>.dkr.ecr.<region>.amazonaws.com/lambda-docker-repo:latest

      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name <lambda-function-name> \
            --image-uri <account-id>.dkr.ecr.<region>.amazonaws.com/lambda-docker-repo:latest
