name: Deploy Lambda Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1  # Specify your AWS region

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker build -t lambda-docker-deploy .
          docker tag lambda-docker-deploy:latest <account-id>.dkr.ecr.us-east-1.amazonaws.com/lambda-docker-repo:latest
          docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/lambda-docker-repo:latest

      - name: Update Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code --function-name <lambda-function-name> \
            --image-uri <account-id>.dkr.ecr.us-east-1.amazonaws.com/lambda-docker-repo:latest
